#!/bin/bash
set -x
# https://github.com/cargo-bins/cargo-binstall
#
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# rustup update
#
# curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

cargo binstall -y tealdeer \
  grex \
  atac \
  ripgrep \
  fd-find \
  bat \
  sd \
  jnv \
  zoxide \
  television \
  fnm

# go install git.sr.ht/~timharek/yr@latest

# go install github.com/mrusme/zeit@latest

go install github.com/junegunn/fzf@latest

go install github.com/mikefarah/yq/v4@latest
