#!/bin/sh
# enter an interactive chat conversation using mods

model=$(yq -r .apis[].models[].aliases[0] ~/.config/mods/mods.yml \
    | gum choose --height 8 --header "Pick model to chat with:" --no-show-help)
if [ -z "$model" ]; then
gum format "  :pensive:  cancelled, no model picked." -t emoji
exit 1
fi
# first invocation starts a new conversation
mods --model "$model" --prompt-args || exit $?
# after that enter a loop until user quits
while mods --model "$model" --prompt-args --continue-last; do :; done
exit $?
