#!/bin/bash

image="$(mktemp -u --suffix=".png")"
scrot -s $image "$@"
# import "png:$image" -strip
notify-send --icon="$image" "Screenshot taken."
xclip -selection clipboard -target image/png "$image"
