#!/bin/bash
# Vim filter to execute SQL queries

if [ -z "${MYSQL_HOST}" ] || [ -z "${MYSQL_USER}" ] || [ -z "${MYSQL_PASSWORD}" ]; then
  echo "MYSQL_HOST, MYSQL_USER and MYSQL_PASSWORD must be set"
  exit 1
fi

SQL=""
while IFS= read -r line; do
  SQL+="$line\n"
done
ESCAPED_SQL="${SQL//\'/\"}"
echo -e "$SQL"
echo "$MYSQL_PASSWORD" | mysql -h"${MYSQL_HOST}" -u"${MYSQL_USER}" -p -D"${MYSQL_DATABASE}" -t -e "${ESCAPED_SQL//\\n/ }"
echo
