#!/bin/bash

REGEX='(((http|https|ftp|gopher)|mailto):(//)?[^ <>"\t]*|(www|ftp)[0-9]?\.[-a-z0-9.]+)[^ .,;\t\n\r<">\):]?[^, <>"\t]*[^ .,;\t\n\r<">\):]'

rg -o "$REGEX" </dev/stdin | \
  fzf \
   --bind 'alt-enter:execute(xdg-open {})+close' \
   --bind 'ctrl-y:execute-silent(echo {} | setsid xclip -selection clipboard)+close' \
   --bind 'ctrl-s:execute-silent(bm add {})+close' \
   --bind 'ctrl-i:execute(feh -FZ {})+close' \
   --bind "enter:become(${BROWSER:-lynx} {})"
